{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "batch"
  resources:
  - "namespaces"
  - "replicationcontrollers"
  - "services"
  - "nodes"
  - "nodes/spec"
  - "pods"
  - "jobs"
  - "cronjobs"
  - "persistentvolumes"
  - "persistentvolumeclaims"
  - "deployments"
  - "replicasets"
  - "daemonsets"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups: [""]
  resources:
  - "services/proxy"
  - "pods/proxy"
  - "nodes/proxy"
  - "nodes/stats"
  verbs:
  - "get"
  - "list"
  - "create"
{{- end }}