{{- if and .Values.serviceAccount.create  .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources:
  - "pods"
  - "pods/log"
  verbs:
  - "get"
  - "list"
{{- end }}